# Form implementation generated from reading ui file 'remote2.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from television import *
from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window, television: type[Television]) -> None:
        '''
        Function to create the intractable window.
        :param window: The ui window itself.
        :param television: The television file to be called upon.
        '''
        self.television = television
        window.setObjectName("window")
        window.resize(103, 188)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(window.sizePolicy().hasHeightForWidth())
        window.setSizePolicy(sizePolicy)
        window.setMinimumSize(QtCore.QSize(103, 188))
        window.setMaximumSize(QtCore.QSize(103, 205))
        self.formLayout = QtWidgets.QFormLayout(window)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.pushButton = QtWidgets.QPushButton(parent=window)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton.clicked.connect(self.television.power)

        self.pushButton_2 = QtWidgets.QPushButton(parent=window)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_2.clicked.connect(self.television.mute)

        self.pushButton_3 = QtWidgets.QPushButton(parent=window)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_3.clicked.connect(self.television.channel_up)

        self.pushButton_4 = QtWidgets.QPushButton(parent=window)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_4.clicked.connect(self.television.channel_down)

        self.pushButton_5 = QtWidgets.QPushButton(parent=window)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 4, 0, 1, 1)
        self.pushButton_5.clicked.connect(self.television.volume_up)

        self.pushButton_6 = QtWidgets.QPushButton(parent=window)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 5, 0, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.gridLayout)
        self.pushButton_6.clicked.connect(self.television.volume_down)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window) -> None:
        '''
        Function that creates the text for each button.
        :param window: The ui window itself.
        '''
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Remote"))
        self.pushButton_2.setText(_translate("window", "Mute"))
        self.pushButton_4.setText(_translate("window", "Channel Down"))
        self.pushButton_3.setText(_translate("window", "Channel Up"))
        self.pushButton_5.setText(_translate("window", "Volume Up"))
        self.pushButton_6.setText(_translate("window", "Volume Down"))
        self.pushButton.setText(_translate("window", "Power"))

import sys
app = QtWidgets.QApplication(sys.argv)
television_instance = Television()
window = QtWidgets.QDialog()
ui = Ui_window()
ui.setupUi(window, television_instance)
window.show()
sys.exit(app.exec())
